apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: paragon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: yourdockerhubusername/paragon-frontend:1.0
          env:
            - name: REACT_APP_API_URL
              value: "http://backend.paragon.svc.cluster.local:5000/api"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: paragon
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
